import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto } from 'next/font/google';
import '../styles/variables.css';
import '../styles/reset.css';
import '../styles/globals.css';
import Header from '@/components/Header/Header';
import Container from '@/components/Container/Container';
import TanstackProvider from '@/components/providers/TanstackProvider';
import AuthInitializer from '@/components/AuthInitializer';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.className}`}
      >
        <TanstackProvider>
          <AuthInitializer>
            <Container>
              <Header />
              {children}
              <Toaster position="top-right" />
            </Container>
          </AuthInitializer>
        </TanstackProvider>
      </body>
    </html>
  );
}
